import os
import subprocess

def get_file_content(path):
    with open(path, 'r', encoding='utf-8', errors='ignore') as f:
        return f.read()

def main():
    base_path = "/home/simond/simes-vault/Work Stuff/Auricom"
    files_to_read = [
        "Corporate Info and Admin/Auricom Limited Summary.md",
        "Corporate Info and Admin/Auricom.uk.md",
        "OpenAi-Auricom.md",
        "TNE  engagement/TNE-Contract  August 2024.md"
    ]
    
    context = ""
    for f in files_to_read:
        full_path = os.path.join(base_path, f)
        if os.path.exists(full_path):
            context += f"\n--- FILE: {f} ---\n"
            context += get_file_content(full_path)
    
    prompt = f"Based on the following files from Simon's vault, provide a concise summary of Auricom Limited. Include its corporate status, key administrative details, and the nature of its engagement with TNE and OpenAI. Format as Markdown for an Obsidian note.\n\n{context}"
    
    # Use ollama directly via CLI
    process = subprocess.Popen(['ollama', 'run', 'qwen2.5-coder:7b', prompt], 
                               stdout=subprocess.PIPE, 
                               stderr=subprocess.PIPE,
                               text=True)
    stdout, stderr = process.communicate()
    
    if stdout:
        output_path = "/home/simond/simes-vault/Notes/Projects/Auricom-Summary.md"
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w") as f:
            f.write("# 🏢 Auricom Limited Summary\n\n")
            f.write(stdout)
        print(f"Summary written to {output_path}")
        
        # Git push
        subprocess.run(["git", "-C", "/home/simond/simes-vault", "add", "Notes/Projects/Auricom-Summary.md"])
        subprocess.run(["git", "-C", "/home/simond/simes-vault", "commit", "-m", "Add Auricom summary generated by local Qwen"])
        subprocess.run(["git", "-C", "/home/simond/simes-vault", "push"])

if __name__ == "__main__":
    main()
